// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";

// src/lib/mcp/_shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { z } from "npm:zod@^4.4.3";
var DEFAULT_LIMIT = 25;
var MAX_LIMIT = 100;
var limitSchema = z.number().int().min(1).max(MAX_LIMIT).default(DEFAULT_LIMIT).describe(`Max rows to return. Default ${DEFAULT_LIMIT}, hard cap ${MAX_LIMIT}.`);
function supabaseForUser(ctx) {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const anon = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function withAudit(toolName, fn) {
  return async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const started = Date.now();
    let status = "ok";
    let errorMessage = null;
    try {
      const result = await fn(input, ctx, sb);
      if (result?._empty) status = "empty";
      return result;
    } catch (err) {
      status = "error";
      errorMessage = err instanceof Error ? err.message : String(err);
      return {
        content: [{ type: "text", text: `Error: ${errorMessage}` }],
        isError: true
      };
    } finally {
      try {
        const { data: profile } = await sb.from("profiles").select("company_id").eq("id", ctx.getUserId()).maybeSingle();
        await sb.from("mcp_audit_log").insert({
          user_id: ctx.getUserId(),
          company_id: profile?.company_id ?? null,
          tool_name: toolName,
          parameters: sanitizeParams(input),
          result_status: status,
          error_message: errorMessage,
          oauth_client_id: ctx.getClientId?.() ?? null
        });
      } catch {
      }
      console.log(`[mcp:${toolName}] ${status} ${Date.now() - started}ms`);
    }
  };
}
function sanitizeParams(input) {
  if (!input || typeof input !== "object") return {};
  const out = {};
  for (const [k, v] of Object.entries(input)) {
    if (/token|secret|password|apikey|bearer/i.test(k)) {
      out[k] = "[redacted]";
    } else {
      out[k] = v;
    }
  }
  return out;
}
function ok(text, structured) {
  const content = [{ type: "text", text }];
  const res = { content };
  if (structured !== void 0) res.structuredContent = structured;
  return res;
}
function empty(text = "No matching rows visible to you.") {
  return { ...ok(text, { rows: [] }), _empty: true };
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List projects visible to the signed-in user (respects RLS and company scoping). Read-only.",
  inputSchema: {
    status: z2.string().optional().describe("Filter by project status, e.g. 'open', 'closed'."),
    client_id: z2.string().uuid().optional().describe("Filter by client UUID."),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("list_projects", async ({ status, client_id, limit }, _ctx, sb) => {
    let q = sb.from("projects").select(
      "id, project_number, name, status, project_type, client_id, property_id, assigned_pm_id, project_complexity_tier, created_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    if (client_id) q = q.eq("client_id", client_id);
    const { data, error } = await q;
    if (error) throw error;
    if (!data?.length) return empty("No projects visible to you.");
    return ok(`Found ${data.length} project(s).`, { rows: data });
  })
});

// src/lib/mcp/tools/search-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var search_projects_default = defineTool2({
  name: "search_projects",
  title: "Search projects",
  description: "Full-text search on project name, number, and address (via property join). Read-only.",
  inputSchema: {
    query: z3.string().min(1).describe("Search text."),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("search_projects", async ({ query, limit }, _ctx, sb) => {
    const pat = `%${query.replace(/[%_]/g, "\\$&")}%`;
    const { data, error } = await sb.from("projects").select(
      "id, project_number, name, status, project_type, client_id, property_id, updated_at"
    ).or(`name.ilike.${pat},project_number.ilike.${pat},tenant_name.ilike.${pat}`).order("updated_at", { ascending: false }).limit(limit);
    if (error) throw error;
    if (!data?.length) return empty(`No projects match "${query}".`);
    return ok(`Found ${data.length} project(s) matching "${query}".`, { rows: data });
  })
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var get_project_default = defineTool3({
  name: "get_project",
  title: "Get project",
  description: "Get full detail for a single project (RLS-scoped). Read-only.",
  inputSchema: { project_id: z4.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("get_project", async ({ project_id }, _ctx, sb) => {
    const { data, error } = await sb.from("projects").select(
      `id, project_number, name, status, project_type, floor_number, unit_number,
         tenant_name, client_id, property_id, assigned_pm_id, senior_pm_id,
         project_complexity_tier, expected_construction_start,
         estimated_construction_completion, actual_construction_start,
         actual_construction_completion, completion_date, is_external, notable,
         created_at, updated_at,
         properties!projects_property_id_fkey ( id, address, borough, bin, block, lot, zip_code ),
         clients!projects_client_id_fkey ( id, name )`
    ).eq("id", project_id).maybeSingle();
    if (error) throw error;
    if (!data) return empty("Project not found or not visible to you.");
    return ok(`Project ${data.project_number ?? data.id}: ${data.name ?? "(unnamed)"}.`, data);
  })
});

// src/lib/mcp/tools/get-project-timeline.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var get_project_timeline_default = defineTool4({
  name: "get_project_timeline",
  title: "Get project timeline",
  description: "List timeline events for a project (most recent first). Read-only.",
  inputSchema: {
    project_id: z5.string().uuid(),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("get_project_timeline", async ({ project_id, limit }, _ctx, sb) => {
    const { data, error } = await sb.from("project_timeline_events").select("id, event_type, description, actor_id, created_at, metadata").eq("project_id", project_id).order("created_at", { ascending: false }).limit(limit);
    if (error) throw error;
    if (!data?.length) return empty("No timeline events for this project.");
    return ok(`Found ${data.length} timeline event(s).`, { rows: data });
  })
});

// src/lib/mcp/tools/list-project-notes.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^4.4.3";
var list_project_notes_default = defineTool5({
  name: "list_project_notes",
  title: "List project notes",
  description: "List notes attached to a project (most recent first). Read-only.",
  inputSchema: {
    project_id: z6.string().uuid(),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("list_project_notes", async ({ project_id, limit }, _ctx, sb) => {
    const { data, error } = await sb.from("project_notes").select("id, body, source, user_id, service_id, client_visible, created_at").eq("project_id", project_id).order("created_at", { ascending: false }).limit(limit);
    if (error) throw error;
    if (!data?.length) return empty("No notes on this project.");
    return ok(`Found ${data.length} note(s).`, { rows: data });
  })
});

// src/lib/mcp/tools/list-project-action-items.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z7 } from "npm:zod@^4.4.3";
var list_project_action_items_default = defineTool6({
  name: "list_project_action_items",
  title: "List project action items",
  description: "List action items for a project. Read-only.",
  inputSchema: {
    project_id: z7.string().uuid(),
    status: z7.string().optional().describe("Filter by status. Default: 'open'."),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit(
    "list_project_action_items",
    async ({ project_id, status, limit }, _ctx, sb) => {
      let q = sb.from("project_action_items").select(
        "id, title, description, status, priority, assigned_to, assigned_by, due_date, completed_at, service_id, created_at"
      ).eq("project_id", project_id).order("due_date", { ascending: true, nullsFirst: false }).limit(limit);
      q = q.eq("status", status ?? "open");
      const { data, error } = await q;
      if (error) throw error;
      if (!data?.length) return empty("No action items match.");
      return ok(`Found ${data.length} action item(s).`, { rows: data });
    }
  )
});

// src/lib/mcp/tools/list-open-action-items.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z8 } from "npm:zod@^4.4.3";
var list_open_action_items_default = defineTool7({
  name: "list_open_action_items",
  title: "List my open action items",
  description: "List open action items across projects. Defaults to items assigned to the signed-in user. Read-only.",
  inputSchema: {
    assignee: z8.string().uuid().optional().describe("Profile UUID of the assignee. Defaults to the signed-in user."),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("list_open_action_items", async ({ assignee, limit }, ctx, sb) => {
    const target = assignee ?? ctx.getUserId();
    const { data, error } = await sb.from("project_action_items").select("id, title, status, priority, due_date, project_id, assigned_to, created_at").eq("assigned_to", target).eq("status", "open").order("due_date", { ascending: true, nullsFirst: false }).limit(limit);
    if (error) throw error;
    if (!data?.length) return empty("No open action items for this user.");
    return ok(`Found ${data.length} open action item(s).`, { rows: data });
  })
});

// src/lib/mcp/tools/list-dob-applications.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z9 } from "npm:zod@^4.4.3";
var list_dob_applications_default = defineTool8({
  name: "list_dob_applications",
  title: "List DOB applications",
  description: "List DOB job filings for a project, property, or BIN. Read-only.",
  inputSchema: {
    project_id: z9.string().uuid().optional(),
    property_id: z9.string().uuid().optional(),
    bin: z9.string().optional().describe("Building Identification Number (BIN)."),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit(
    "list_dob_applications",
    async ({ project_id, property_id, bin, limit }, _ctx, sb) => {
      let propIds;
      if (bin) {
        const { data: props } = await sb.from("properties").select("id").eq("bin", bin);
        propIds = props?.map((p) => p.id) ?? [];
        if (!propIds.length) return empty(`No properties found for BIN ${bin}.`);
      }
      let q = sb.from("dob_applications").select(
        "id, job_number, application_type, status, examiner_name, filed_date, approved_date, permit_issued_date, project_id, property_id, updated_at"
      ).order("filed_date", { ascending: false, nullsFirst: false }).limit(limit);
      if (project_id) q = q.eq("project_id", project_id);
      if (property_id) q = q.eq("property_id", property_id);
      if (propIds) q = q.in("property_id", propIds);
      const { data, error } = await q;
      if (error) throw error;
      if (!data?.length) return empty("No DOB applications match.");
      return ok(`Found ${data.length} DOB application(s).`, { rows: data });
    }
  )
});

// src/lib/mcp/tools/get-dob-application.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z10 } from "npm:zod@^4.4.3";
var get_dob_application_default = defineTool9({
  name: "get_dob_application",
  title: "Get DOB application",
  description: "Get full detail for a single DOB application. Read-only.",
  inputSchema: { application_id: z10.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("get_dob_application", async ({ application_id }, _ctx, sb) => {
    const { data, error } = await sb.from("dob_applications").select("*").eq("id", application_id).maybeSingle();
    if (error) throw error;
    if (!data) return empty("DOB application not found or not visible to you.");
    return ok(`DOB application ${data.job_number ?? data.id}.`, data);
  })
});

// src/lib/mcp/tools/list-filings.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z11 } from "npm:zod@^4.4.3";
var list_filings_default = defineTool10({
  name: "list_filings",
  title: "List filings",
  description: "List filing records for a project. Read-only.",
  inputSchema: {
    project_id: z11.string().uuid(),
    status: z11.string().optional().describe("Filter by current_stage."),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("list_filings", async ({ project_id, status, limit }, _ctx, sb) => {
    let q = sb.from("filings").select(
      "id, discipline, agency, filing_number, current_stage, stage_entered_at, expected_next_milestone, blocked, blocked_reason, blocked_since, updated_at"
    ).eq("project_id", project_id).order("updated_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("current_stage", status);
    const { data, error } = await q;
    if (error) throw error;
    if (!data?.length) return empty("No filings for this project.");
    return ok(`Found ${data.length} filing(s).`, { rows: data });
  })
});

// src/lib/mcp/tools/search-clients.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z12 } from "npm:zod@^4.4.3";
var CLIENT_FIELDS = "id, name, email, phone, address, client_type, is_sia, is_rfp_partner, specialty_tags, licensed_jurisdictions, hic_license, dob_tracking, dob_tracking_expiration, created_at, updated_at";
var search_clients_default = defineTool11({
  name: "search_clients",
  title: "Search clients",
  description: "Search clients by name, email, or phone. Excludes internal notes and financial/tier fields. Read-only.",
  inputSchema: {
    query: z12.string().min(1),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("search_clients", async ({ query, limit }, _ctx, sb) => {
    const pat = `%${query.replace(/[%_]/g, "\\$&")}%`;
    const { data, error } = await sb.from("clients").select(CLIENT_FIELDS).or(`name.ilike.${pat},email.ilike.${pat},phone.ilike.${pat}`).order("name", { ascending: true }).limit(limit);
    if (error) throw error;
    if (!data?.length) return empty(`No clients match "${query}".`);
    return ok(`Found ${data.length} client(s).`, { rows: data });
  })
});

// src/lib/mcp/tools/get-client.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z13 } from "npm:zod@^4.4.3";
var CLIENT_FIELDS2 = "id, name, email, phone, fax, address, client_type, is_sia, is_rfp_partner, specialty_tags, licensed_jurisdictions, tax_id, ibm_number, ibm_number_expiration, hic_license, dob_tracking, dob_tracking_expiration, created_at, updated_at";
var get_client_default = defineTool12({
  name: "get_client",
  title: "Get client",
  description: "Get a client record. Excludes internal_notes, expected_annual_value, expected_projects_per_year, and client_tier. Read-only.",
  inputSchema: { client_id: z13.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("get_client", async ({ client_id }, _ctx, sb) => {
    const { data, error } = await sb.from("clients").select(CLIENT_FIELDS2).eq("id", client_id).maybeSingle();
    if (error) throw error;
    if (!data) return empty("Client not found or not visible to you.");
    return ok(`Client: ${data.name}.`, data);
  })
});

// src/lib/mcp/tools/search-contacts.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z14 } from "npm:zod@^4.4.3";
var CONTACT_FIELDS = "id, client_id, name, first_name, last_name, title, email, phone, mobile, is_primary, license_type, license_number, specialty, licensed_jurisdictions, is_referrer, created_at";
var search_contacts_default = defineTool13({
  name: "search_contacts",
  title: "Search client contacts",
  description: "Search client contacts by name, email, or phone. Read-only.",
  inputSchema: {
    query: z14.string().min(1),
    client_id: z14.string().uuid().optional(),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("search_contacts", async ({ query, client_id, limit }, _ctx, sb) => {
    const pat = `%${query.replace(/[%_]/g, "\\$&")}%`;
    let q = sb.from("client_contacts").select(CONTACT_FIELDS).or(`name.ilike.${pat},email.ilike.${pat},phone.ilike.${pat},mobile.ilike.${pat}`).order("name", { ascending: true }).limit(limit);
    if (client_id) q = q.eq("client_id", client_id);
    const { data, error } = await q;
    if (error) throw error;
    if (!data?.length) return empty(`No contacts match "${query}".`);
    return ok(`Found ${data.length} contact(s).`, { rows: data });
  })
});

// src/lib/mcp/tools/list-properties.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z15 } from "npm:zod@^4.4.3";
var PROP_FIELDS = "id, address, borough, block, lot, bin, zip_code, owner_name, created_at, updated_at";
var list_properties_default = defineTool14({
  name: "list_properties",
  title: "List properties",
  description: "List / search properties. Provide a text query, a client_id, or neither for the most recent set. Read-only.",
  inputSchema: {
    query: z15.string().optional().describe("Search text on address, BIN, block/lot."),
    limit: limitSchema
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("list_properties", async ({ query, limit }, _ctx, sb) => {
    let q = sb.from("properties").select(PROP_FIELDS).order("updated_at", { ascending: false }).limit(limit);
    if (query) {
      const pat = `%${query.replace(/[%_]/g, "\\$&")}%`;
      q = q.or(`address.ilike.${pat},bin.ilike.${pat},block.ilike.${pat},lot.ilike.${pat}`);
    }
    const { data, error } = await q;
    if (error) throw error;
    if (!data?.length) return empty("No properties visible to you.");
    return ok(`Found ${data.length} property(ies).`, { rows: data });
  })
});

// src/lib/mcp/tools/get-property.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z16 } from "npm:zod@^4.4.3";
var get_property_default = defineTool15({
  name: "get_property",
  title: "Get property",
  description: "Get a single property record. Read-only.",
  inputSchema: { property_id: z16.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withAudit("get_property", async ({ property_id }, _ctx, sb) => {
    const { data, error } = await sb.from("properties").select("*").eq("id", property_id).maybeSingle();
    if (error) throw error;
    if (!data) return empty("Property not found or not visible to you.");
    return ok(`Property: ${data.address}.`, data);
  })
});

// src/lib/mcp/index.ts
var projectRef = "mimlfjkisguktiqqkpkm";
var mcp_default = defineMcp({
  name: "ordino-mcp",
  title: "Ordino",
  version: "0.1.0",
  instructions: [
    "Ordino is Green Light Expediting's NYC construction expediting CRM.",
    "All tools are READ-ONLY and run as the signed-in user (respects row-level",
    "security and per-company scoping). Every call is written to an audit log.",
    "Use search_* tools to find records, then get_* / list_* to drill in.",
    "Financial data (invoices, billing amounts, employee compensation),",
    "internal staff notes, settings, and Beacon analytics are intentionally",
    "not exposed."
  ].join(" "),
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_projects_default,
    search_projects_default,
    get_project_default,
    get_project_timeline_default,
    list_project_notes_default,
    list_project_action_items_default,
    list_open_action_items_default,
    list_dob_applications_default,
    get_dob_application_default,
    list_filings_default,
    search_clients_default,
    get_client_default,
    search_contacts_default,
    list_properties_default,
    get_property_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
