import type { ServiceCatalogItem } from "@/hooks/useCompanySettings";

export const DEFAULT_SERVICES: Omit<ServiceCatalogItem, "id">[] = [
  { name: "ALT-2 D14 Approval - Regular", default_price: 950, default_hours: 3, multiplier: 2.81 },
  { name: "ALT-2 D14 Approval - Rudin", default_price: 2000, default_hours: 2, multiplier: 8.89 },
  { name: "ALT-2 Non-D14 Approval", default_price: 3500, default_hours: 5, multiplier: 6.22 },
  { name: "ALT-1/ALT CO Approval", default_price: 6500, default_hours: 9, multiplier: 6.42 },
  { name: "New Building Approval", default_price: 10000, default_hours: 15, multiplier: 5.92 },
  { name: "Work Permit", default_price: 250, default_hours: 1, multiplier: 2.22 },
  { name: "Letter of Completion", default_price: 750, default_hours: 1, multiplier: 6.66 },
  { name: "Certificate of Occupancy", default_price: 12000, default_hours: 15, multiplier: 7.11 },
  { name: "Temporary Certificate of Occupancy", default_price: 13000, default_hours: 20, multiplier: 5.78 },
  { name: "PAA - Post Approval Amendment - Big Change", default_price: 3500, default_hours: 4, multiplier: 7.78 },
  { name: "PAA - Post Approval Amendment", default_price: 950, default_hours: 2, multiplier: 4.22 },
  { name: "Place of Assembly Approval", default_price: 3000, default_hours: 4, multiplier: 6.66 },
  { name: "Landmarks Preservation Commission Approval", default_price: 750, default_hours: 2, multiplier: 3.33 },
  { name: "Equipment Use Permit", default_price: 350, default_hours: 0.5, multiplier: 6.22 },
  { name: "Reinstatement", default_price: 1050, default_hours: 2.5, multiplier: 3.73 },
  { name: "Withdrawal", default_price: 1050, default_hours: 3, multiplier: 3.11 },
  { name: "Civil Penalty Waiver", default_price: 1050, default_hours: 3, multiplier: 3.11 },
  { name: "Remove ECB Violation", default_price: 950, default_hours: 3, multiplier: 2.81 },
  { name: "Demolition Filing", default_price: 4500, default_hours: 5, multiplier: 8.00 },
  { name: "BPP Approval and Permit", default_price: 5500, default_hours: 6, multiplier: 8.15 },
  { name: "Letter of No Objection", default_price: 3000, default_hours: 7, multiplier: 3.81 },
  { name: "DOT Sidewalk Permit", default_price: 350, default_hours: 1, multiplier: 3.11 },
  { name: "DOB Tracking Number", default_price: 300, default_hours: 0.5, multiplier: 5.33 },
  { name: "DOT IBM Number", default_price: 1800, default_hours: 5, multiplier: 3.20 },
  { name: "After Hours Permit - Initial", default_price: 500, default_hours: 3, multiplier: 1.48 },
  { name: "After Hours Permit", default_price: 350, default_hours: 1, multiplier: 3.11 },
  { name: "Energy Code Compliance Submission", default_price: 450, default_hours: 1.5, multiplier: 2.67 },
  { name: "Solar Application Approval", default_price: 3300, default_hours: 4, multiplier: 7.33 },
  { name: "DOB Inspection Attendance", default_price: 1500, default_hours: 4, multiplier: 3.33 },
  { name: "Final Electrical Sign-Off", default_price: 750, default_hours: 1, multiplier: 6.66 },
  { name: "Final Plumbing Sign-Off", default_price: 750, default_hours: 1.5, multiplier: 4.44 },
  { name: "Final Sprinkler Sign-Off", default_price: 750, default_hours: 1.5, multiplier: 4.44 },
  { name: "Final Elevator Sign-Off", default_price: 750, default_hours: 1, multiplier: 6.66 },
  { name: "Final Construction Sign-Off", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "Address Verification", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "FDNY Violation Removal", default_price: 750, default_hours: 1, multiplier: 6.66 },
  { name: "DOT Permit", default_price: 1000, default_hours: 2, multiplier: 4.44 },
  { name: "TR2/TR3 Coordination", default_price: 1200, default_hours: 2, multiplier: 5.33 },
  { name: "Required Item Waiver", default_price: 950, default_hours: 1, multiplier: 8.44 },
  { name: "Tenant Protection Plan (TPP) Submission", default_price: 350, default_hours: 1, multiplier: 3.11 },
  { name: "Form Preparation", default_price: 750, default_hours: 3, multiplier: 2.22 },
  { name: "Project Coordination", default_price: 500, default_hours: 1, multiplier: 4.44 },
  { name: "Schedule Final Inspection", default_price: 450, default_hours: 1, multiplier: 4.00 },
  { name: "Stop Work Order", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "Determination Filings", default_price: 2500, default_hours: 5, multiplier: 4.44 },
  { name: "Permit Renewal", default_price: 300, default_hours: 0.5, multiplier: 5.33 },
  { name: "TPA", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "Reassignment", default_price: 950, default_hours: 2, multiplier: 4.22 },
  { name: "OER Approval", default_price: 750, default_hours: 1.5, multiplier: 4.44 },
  { name: "Subdivision Approval", default_price: 3500, default_hours: 5, multiplier: 6.22 },
  { name: "Obtain New Tax Lots with DOF", default_price: 2000, default_hours: 1, multiplier: 17.77 },
  { name: "Asbestos Coordination", default_price: 350, default_hours: 1, multiplier: 3.11 },
  { name: "TCO Renewals", default_price: 1200, default_hours: 2, multiplier: 5.33 },
  { name: "Fire Protection Plan", default_price: 7500, default_hours: 9, multiplier: 7.40 },
  { name: "Remove Vacate Order", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "DOT Vault Approval", default_price: 9000, default_hours: 10, multiplier: 8.00 },
  { name: "FDNY Rooftop Access", default_price: 3000, default_hours: 5, multiplier: 5.33 },
  { name: "OER Little E Submission", default_price: 750, default_hours: 1.5, multiplier: 4.44 },
  { name: "MTA Approval", default_price: 13000, default_hours: 15, multiplier: 7.70 },
  { name: "DOT New Building Meeting", default_price: 3000, default_hours: 5, multiplier: 5.33 },
  { name: "DOT Revocable Consent", default_price: 25000, default_hours: 25, multiplier: 8.89 },
  { name: "10 Day Notices", default_price: 350, default_hours: 1, multiplier: 3.11 },
  { name: "Fire Alarm Approval", default_price: 2000, default_hours: 4, multiplier: 4.44 },
  { name: "Schedule of Occupancy Transfer", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "Verify Tax Lot", default_price: 350, default_hours: 0.5, multiplier: 6.22 },
];
