import type { ServiceCatalogItem } from "@/hooks/useCompanySettings";

export const DEFAULT_SERVICES: Omit<ServiceCatalogItem, "id">[] = [
  { name: "ALT-2 D14 Approval - Regular", description: "Standard Alteration Type 2 filing for D14 code-compliant work scopes", default_price: 950, default_hours: 3, multiplier: 2.81 },
  { name: "ALT-2 D14 Approval - Rudin", description: "ALT-2 D14 filing customized for Rudin Management properties", default_price: 2000, default_hours: 2, multiplier: 8.89 },
  { name: "ALT-2 Non-D14 Approval", description: "Alteration Type 2 filing for work scopes outside D14 classification", default_price: 3500, default_hours: 5, multiplier: 6.22 },
  { name: "ALT-1/ALT CO Approval", description: "Alteration Type 1 or CO-required alteration filing with full plan review", default_price: 6500, default_hours: 9, multiplier: 6.42 },
  { name: "New Building Approval", description: "Full new building application filing through DOB NOW plan examination", default_price: 10000, default_hours: 15, multiplier: 5.92 },
  { name: "Work Permit", description: "Permit application for approved job filings to commence construction", default_price: 250, default_hours: 1, multiplier: 2.22 },
  { name: "Letter of Completion", description: "Filing to certify all approved work has been completed per plans", default_price: 750, default_hours: 1, multiplier: 6.66 },
  { name: "Certificate of Occupancy", description: "Final CO application including scheduling and coordinating all required sign-offs", default_price: 12000, default_hours: 15, multiplier: 7.11 },
  { name: "Temporary Certificate of Occupancy", description: "TCO application for interim occupancy while outstanding items are resolved", default_price: 13000, default_hours: 20, multiplier: 5.78 },
  { name: "PAA - Post Approval Amendment - Big Change", description: "Major post-approval amendment involving significant scope or plan changes", default_price: 3500, default_hours: 4, multiplier: 7.78 },
  { name: "PAA - Post Approval Amendment", description: "Minor post-approval amendment for small scope adjustments after initial approval", default_price: 950, default_hours: 2, multiplier: 4.22 },
  { name: "Place of Assembly Approval", description: "PA permit application for venues exceeding occupancy thresholds", default_price: 3000, default_hours: 4, multiplier: 6.66 },
  { name: "Landmarks Preservation Commission Approval", description: "LPC filing for work on designated landmark buildings or within historic districts", default_price: 750, default_hours: 2, multiplier: 3.33 },
  { name: "Equipment Use Permit", description: "Permit for temporary construction equipment such as hoists, cranes, or scaffolding", default_price: 350, default_hours: 0.5, multiplier: 6.22 },
  { name: "Reinstatement", description: "Application to reinstate a previously withdrawn or lapsed DOB filing", default_price: 1050, default_hours: 2.5, multiplier: 3.73 },
  { name: "Withdrawal", description: "Formal withdrawal of an active DOB application or permit", default_price: 1050, default_hours: 3, multiplier: 3.11 },
  { name: "Civil Penalty Waiver", description: "Request to waive civil penalties associated with DOB violations", default_price: 1050, default_hours: 3, multiplier: 3.11 },
  { name: "Remove ECB Violation", description: "Resolution and removal of Environmental Control Board violations", default_price: 950, default_hours: 3, multiplier: 2.81 },
  { name: "Demolition Filing", description: "Full or partial demolition application including asbestos and utility coordination", default_price: 4500, default_hours: 5, multiplier: 8.00 },
  { name: "BPP Approval and Permit", description: "Builder's Pavement Plan approval and associated sidewalk/roadway permits", default_price: 5500, default_hours: 6, multiplier: 8.15 },
  { name: "Letter of No Objection", description: "DOB letter confirming no objection to proposed use or condition at premises", default_price: 3000, default_hours: 7, multiplier: 3.81 },
  { name: "DOT Sidewalk Permit", description: "Department of Transportation permit for sidewalk construction or repair", default_price: 350, default_hours: 1, multiplier: 3.11 },
  { name: "DOB Tracking Number", description: "Registration of a new DOB tracking number for project monitoring", default_price: 300, default_hours: 0.5, multiplier: 5.33 },
  { name: "DOT IBM Number", description: "DOT Interim Business Measures number for maintaining pedestrian access during construction", default_price: 1800, default_hours: 5, multiplier: 3.20 },
  { name: "After Hours Permit - Initial", description: "Initial after-hours variance permit application for work outside standard hours", default_price: 500, default_hours: 3, multiplier: 1.48 },
  { name: "After Hours Permit", description: "Renewal or standard after-hours work permit for ongoing construction", default_price: 350, default_hours: 1, multiplier: 3.11 },
  { name: "Energy Code Compliance Submission", description: "NYC Energy Conservation Code compliance documentation and filing", default_price: 450, default_hours: 1.5, multiplier: 2.67 },
  { name: "Solar Application Approval", description: "Solar panel installation filing including structural and electrical review", default_price: 3300, default_hours: 4, multiplier: 7.33 },
  { name: "DOB Inspection Attendance", description: "On-site attendance and coordination during scheduled DOB inspections", default_price: 1500, default_hours: 4, multiplier: 3.33 },
  { name: "Final Electrical Sign-Off", description: "Coordination of final electrical inspection and sign-off with DOB", default_price: 750, default_hours: 1, multiplier: 6.66 },
  { name: "Final Plumbing Sign-Off", description: "Coordination of final plumbing inspection and sign-off with DOB", default_price: 750, default_hours: 1.5, multiplier: 4.44 },
  { name: "Final Sprinkler Sign-Off", description: "Coordination of final sprinkler system inspection and sign-off", default_price: 750, default_hours: 1.5, multiplier: 4.44 },
  { name: "Final Elevator Sign-Off", description: "Coordination of final elevator inspection and sign-off with DOB", default_price: 750, default_hours: 1, multiplier: 6.66 },
  { name: "Final Construction Sign-Off", description: "General construction final inspection coordination and sign-off", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "Address Verification", description: "Verification and correction of property address records with DOB/DOF", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "FDNY Violation Removal", description: "Resolution and removal of Fire Department violations from property record", default_price: 750, default_hours: 1, multiplier: 6.66 },
  { name: "DOT Permit", description: "General Department of Transportation permit for street or sidewalk work", default_price: 1000, default_hours: 2, multiplier: 4.44 },
  { name: "TR2/TR3 Coordination", description: "Technical report coordination for post-inspection compliance documentation", default_price: 1200, default_hours: 2, multiplier: 5.33 },
  { name: "Required Item Waiver", description: "Application to waive specific DOB required items or objections", default_price: 950, default_hours: 1, multiplier: 8.44 },
  { name: "Tenant Protection Plan (TPP) Submission", description: "Filing of required tenant protection plan for occupied building construction", default_price: 350, default_hours: 1, multiplier: 3.11 },
  { name: "Form Preparation", description: "Preparation of DOB-required forms, affidavits, or supporting documents", default_price: 750, default_hours: 3, multiplier: 2.22 },
  { name: "Project Coordination", description: "General project coordination including stakeholder communication and scheduling", default_price: 500, default_hours: 1, multiplier: 4.44 },
  { name: "Schedule Final Inspection", description: "Scheduling and coordination of final DOB inspection appointments", default_price: 450, default_hours: 1, multiplier: 4.00 },
  { name: "Stop Work Order", description: "Response and resolution of DOB Stop Work Orders including compliance plan", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "Determination Filings", description: "DOB determination letter filings for zoning or code interpretation requests", default_price: 2500, default_hours: 5, multiplier: 4.44 },
  { name: "Permit Renewal", description: "Renewal of expiring DOB work permits to maintain active status", default_price: 300, default_hours: 0.5, multiplier: 5.33 },
  { name: "TPA", description: "Temporary Place of Assembly permit for short-term event occupancy", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "Reassignment", description: "Transfer of DOB application or job filing to a new applicant of record", default_price: 950, default_hours: 2, multiplier: 4.22 },
  { name: "OER Approval", description: "Office of Environmental Remediation approval for contaminated site work", default_price: 750, default_hours: 1.5, multiplier: 4.44 },
  { name: "Subdivision Approval", description: "Filing for lot subdivision or merger through DOB and DOF", default_price: 3500, default_hours: 5, multiplier: 6.22 },
  { name: "Obtain New Tax Lots with DOF", description: "Creation of new tax lot numbers with Department of Finance post-subdivision", default_price: 2000, default_hours: 1, multiplier: 17.77 },
  { name: "Asbestos Coordination", description: "ACP-5/ACP-7 filing coordination for asbestos abatement compliance", default_price: 350, default_hours: 1, multiplier: 3.11 },
  { name: "TCO Renewals", description: "Renewal of expiring Temporary Certificates of Occupancy", default_price: 1200, default_hours: 2, multiplier: 5.33 },
  { name: "Fire Protection Plan", description: "Comprehensive fire protection plan preparation and FDNY coordination", default_price: 7500, default_hours: 9, multiplier: 7.40 },
  { name: "Remove Vacate Order", description: "Resolution of DOB vacate order to restore legal occupancy", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "DOT Vault Approval", description: "Department of Transportation vault permit for subsurface utility or storage vaults", default_price: 9000, default_hours: 10, multiplier: 8.00 },
  { name: "FDNY Rooftop Access", description: "FDNY rooftop access compliance filing for fire department roof entry requirements", default_price: 3000, default_hours: 5, multiplier: 5.33 },
  { name: "OER Little E Submission", description: "OER 'e' designation environmental review submission for restricted lots", default_price: 750, default_hours: 1.5, multiplier: 4.44 },
  { name: "MTA Approval", description: "Metropolitan Transportation Authority approval for projects near transit infrastructure", default_price: 13000, default_hours: 15, multiplier: 7.70 },
  { name: "DOT New Building Meeting", description: "Pre-construction meeting with DOT for new building sidewalk and roadway impact", default_price: 3000, default_hours: 5, multiplier: 5.33 },
  { name: "DOT Revocable Consent", description: "Revocable consent application for permanent structures in public right-of-way", default_price: 25000, default_hours: 25, multiplier: 8.89 },
  { name: "10 Day Notices", description: "Filing of 10-day advance notice to DOB prior to construction commencement", default_price: 350, default_hours: 1, multiplier: 3.11 },
  { name: "Fire Alarm Approval", description: "Fire alarm system filing and approval coordination with FDNY", default_price: 2000, default_hours: 4, multiplier: 4.44 },
  { name: "Schedule of Occupancy Transfer", description: "Transfer of existing Certificate of Occupancy schedule to new owner or use", default_price: 1200, default_hours: 3, multiplier: 3.55 },
  { name: "Verify Tax Lot", description: "Verification of tax lot information with DOF for filing accuracy", default_price: 350, default_hours: 0.5, multiplier: 6.22 },
];
